import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api";
import { useAsync, useJob, fmtDate } from "../hooks";
import {
  Badge,
  Breadcrumbs,
  Button,
  Card,
  Empty,
  ErrorNote,
  Loading,
  PageHeader,
  Table,
  Td,
} from "../components/ui";

export default function Specs() {
  const { paperId = "" } = useParams();
  const paper = useAsync(() => api.getPaper(paperId), [paperId]);
  const { data: specs, loading, error, reload } = useAsync(() => api.listSpecs(paperId), [paperId]);
  const [jobId, setJobId] = useState<string | null>(null);
  const job = useJob(jobId);
  const [err, setErr] = useState<string | null>(null);

  const generate = async () => {
    setErr(null);
    try {
      const { job_id } = await api.generateSpec(paperId);
      setJobId(job_id);
    } catch (e) {
      setErr((e as Error).message);
    }
  };

  const done = job && job.status !== "running";
  return (
    <>
      <Breadcrumbs
        items={[
          { label: "Papers", to: "/papers" },
          { label: paper.data?.title || paperId, to: `/papers/${paperId}` },
          { label: "Specs" },
        ]}
      />
      <PageHeader
        kicker="Implementation specification"
        title="Specifications"
        sub="The bridge between paper and code: every requirement carries a type, a provenance tag (EXPLICIT / INFERRED / EXTERNAL / UNKNOWN), and a verbatim quote."
        right={
          <Button onClick={generate} busy={job?.status === "running"}>
            Generate spec
          </Button>
        }
      />

      {err && <div className="mb-4"><ErrorNote message={err} /></div>}
      {jobId && done && (
        <div className="mb-4">
          <Card>
            <div className="flex items-center justify-between">
              <span className="text-sm">
                {job?.status === "done" ? (
                  <span className="text-ok">
                    Spec ready —{" "}
                    {(() => {
                      const r = (job?.result ?? {}) as { spec_id?: string; requirements?: number };
                      return r.spec_id ? (
                        <Link className="underline" to={`/specs/${r.spec_id}`}>
                          review {r.requirements ?? "?"} requirements
                        </Link>
                      ) : (
                        "review it"
                      );
                    })()}
                  </span>
                ) : (
                  <span className="text-danger">Spec generation failed: {job?.error}</span>
                )}
              </span>
              <Button
                kind="ghost"
                onClick={() => {
                  setJobId(null);
                  reload();
                }}
              >
                Dismiss
              </Button>
            </div>
          </Card>
        </div>
      )}
      {jobId && !done && (
        <div className="mb-4">
          <Card>
            <div className="flex items-center justify-between">
              <span className="text-sm">
                Building spec… {job?.detail ?? ""} ({Math.round(job?.progress ?? 0)}%)
              </span>
            </div>
            <div className="h-1 bg-panel rounded-full mt-3 overflow-hidden border border-line/60">
              <div
                className="h-full bg-accent transition-all duration-300"
                style={{ width: `${job?.progress ?? 0}%` }}
              />
            </div>
          </Card>
        </div>
      )}

      {error && <ErrorNote message={error} />}
      {loading ? (
        <Loading label="Loading specs…" />
      ) : (specs ?? []).length === 0 ? (
        <Empty
          title="No specifications yet"
          hint="Generate one from the paper's evidence. Offline, the rule extractor produces EXPLICIT requirements with quotes; with an LLM, inferred ones too."
        />
      ) : (
        <Card pad={false} className="animate-rise">
          <Table
            head={[
              { label: "Spec" },
              { label: "Generated by" },
              { label: "Version" },
              { label: "Created" },
              { label: "", className: "text-right" },
            ]}
          >
            {(specs ?? []).map((s) => (
              <tr key={s.id} className="hover:bg-panel/50 transition-colors">
                <Td>
                  <Link to={`/specs/${s.id}`} className="font-medium hover:text-accent">
                    {s.title || s.id}
                  </Link>
                  <div className="text-xs text-ink-faint font-mono mt-0.5">{s.id}</div>
                </Td>
                <Td>
                  <Badge tone={s.generated_by?.includes("llm") ? "accent" : "neutral"}>
                    {s.generated_by ?? "—"}
                  </Badge>
                </Td>
                <Td>v{s.version}</Td>
                <Td>{fmtDate(s.created_at)}</Td>
                <Td className="text-right">
                  <Link to={`/specs/${s.id}`} className="text-xs text-accent hover:underline">
                    review →
                  </Link>
                </Td>
              </tr>
            ))}
          </Table>
        </Card>
      )}
    </>
  );
}
