"""Deterministic project scaffolding from an ImplementationSpec.

The scaffold is a *real, runnable* project skeleton:

* config.yaml carries every hyperparameter requirement as a key with its
  requirement id (traceability: config → spec requirement → paper page),
* source modules are structured with TODO(REQ-xxx) markers where the
  paper requires an implementation decision,
* tests/test_smoke.py and run_smoke.sh are genuinely executable and are
  used by the validation stage,
* values the paper does NOT specify are left as null with a comment —
  never invented.

An LLM can later regenerate/fill individual files (see generator.py); the
scaffold format is stable either way.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from researchrag.models.retrieval import (
    ImplementationSpec,
    RequirementType,
)


def project_slug(title: str | None) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (title or "paper").lower()).strip("-")
    return slug[:48] or "paper"


@dataclass
class GeneratedFile:
    path: str
    content: str
    kind: str = "source"  # source | config | test | script | doc | deps


# ---------------------------------------------------------------------------
# config.yaml
# ---------------------------------------------------------------------------

def _config_yaml(spec: ImplementationSpec) -> str:
    lines = [
        "# Generated by Research RAG from implementation spec",
        f"# Spec: {spec.id}",
        "# Each key is tagged with the spec requirement id it came from",
        "# (REQ-xxx) and its provenance. null = not specified in the paper.",
        "",
        "paper:",
        f'  title: "{spec.title}"',
        "",
        "requirements:",
    ]
    reqs = spec.requirements
    if not reqs:
        lines.append("  {}")
    for r in reqs:
        value = _requirement_value(r)
        lines.append(f"  # {r.id} [{r.type.value}/{r.source.value}] {r.requirement}")
        if r.source_page:
            lines.append(f"  #   source: p.{r.source_page} {r.source_section or ''}".rstrip())
        if r.source_quote:
            lines.append(f'  #   quote: "{r.source_quote[:100]}"')
        lines.append(f"  - id: {r.id}")
        lines.append(f"    type: {r.type.value}")
        lines.append(f"    source: {r.source.value}")
        lines.append(f'    statement: "{_yaml_escape(r.requirement)}"')
        lines.append(f"    value: {_yaml_value(value)}")
        lines.append("")
    lines += [
        "hyperparameters:",
        "  # null means: the paper does not specify this — decide and document it.",
    ]
    hp = spec.requirements_by_type(RequirementType.HYPERPARAMETER)
    found: dict[str, str] = {}
    for r in hp:
        found[r.requirement.lower()] = r.requirement
    defaults = [
        "learning_rate",
        "batch_size",
        "weight_decay",
        "warmup_steps",
        "dropout",
        "top_k",
        "seed",
    ]
    for key in defaults:
        matched = next(
            (
                r
                for r in hp
                if key.split("_")[0] in r.requirement.lower()
            ),
            None,
        )
        if matched:
            val = _requirement_value(matched)
            lines.append(
                f"  {key}: {_yaml_value(val)}  # {matched.id} ({matched.source.value})"
            )
        else:
            lines.append(f"  {key}: null  # not specified in paper")
    return "\n".join(lines) + "\n"


def _requirement_value(r) -> str | None:
    m = re.search(r":\s*([0-9eE.\-+]+|[\w\-]+)\s*$", r.requirement)
    if m:
        return m.group(1)
    return None


def _yaml_value(v: str | None) -> str:
    if v is None:
        return "null"
    try:
        float(v)
        return v
    except ValueError:
        return f'"{v}"'


def _yaml_escape(s: str) -> str:
    return s.replace('"', "'")


# ---------------------------------------------------------------------------
# source files
# ---------------------------------------------------------------------------

def _requirements_block(spec: ImplementationSpec, rtype: RequirementType) -> str:
    reqs = spec.requirements_by_type(rtype)
    if not reqs:
        return "    # (none extracted — review the paper manually)\n"
    out = []
    for r in reqs:
        page = f" p.{r.source_page}" if r.source_page else ""
        out.append(f"    # {r.id} [{r.source.value}]{page} {r.requirement}\n")
    return "".join(out)


def _model_py(spec: ImplementationSpec, slug: str) -> str:
    arch = _requirements_block(spec, RequirementType.ARCHITECTURE)
    model = _requirements_block(spec, RequirementType.MODEL)
    loss = _requirements_block(spec, RequirementType.LOSS)
    return f'''"""Model definition for {_yaml_escape(slug)} (generated scaffold).

Fill each TODO with the implementation required by the tagged requirement.
"""

# Architecture requirements:
{arch}
# Model component requirements:
{model}
# Loss requirements:
{loss}


def build_model(config: dict):
    """Construct the model described by the paper.

    TODO: implement using the architecture requirements above.
    The config dict comes from config.yaml (see `hyperparameters`).
    """
    raise NotImplementedError(
        "Model not yet implemented. See requirements tagged in this file."
    )


def loss_fn(model, batch, target):
    """Loss function for training.

    TODO: implement per the loss requirements above.
    """
    raise NotImplementedError
'''


def _data_py(spec: ImplementationSpec, slug: str) -> str:
    ds = _requirements_block(spec, RequirementType.DATASET)
    pre = _requirements_block(spec, RequirementType.PREPROCESSING)
    return f'''"""Data loading and preprocessing for {_yaml_escape(slug)} (generated scaffold).

# Dataset requirements:
{ds}# Preprocessing requirements:
{pre}
"""


def load_datasets(config: dict):
    """Return (train, dev, test) datasets.

    TODO: implement per the dataset requirements above (splits, fields).
    """
    raise NotImplementedError
'''


def _train_py(spec: ImplementationSpec, slug: str) -> str:
    tr = _requirements_block(spec, RequirementType.TRAINING)
    opt = _requirements_block(spec, RequirementType.OPTIMIZER)
    hp = _requirements_block(spec, RequirementType.HYPERPARAMETER)
    hw = _requirements_block(spec, RequirementType.HARDWARE)
    return f'''"""Training loop for {_yaml_escape(slug)} (generated scaffold).

Run:  python -m {slug.replace('-', '_')}.train --config config.yaml
"""

# Training procedure requirements:
{tr}# Optimizer requirements:
{opt}# Hyperparameters:
{hp}# Hardware:
{hw}


def train(config: dict):
    """Train the model. Returns a dict of final metrics.

    TODO: implement the training loop with the optimizer, schedule, batch
    size and duration specified by the requirements above.
    End by printing:  METRICS: <json>
    """
    raise NotImplementedError
'''


def _evaluate_py(slug: str) -> str:
    return f'''"""Evaluation for {_yaml_escape(slug)} (generated scaffold).

Run:  python -m {slug.replace('-', '_')}.evaluate --config config.yaml
"""


def evaluate(config: dict):
    """Evaluate on the paper's test splits and print METRICS: <json>."""
    raise NotImplementedError
'''


def _infer_py(slug: str) -> str:
    return f'''"""Inference for {_yaml_escape(slug)} (generated scaffold).

Run:  python -m {slug.replace('-', '_')}.infer --config config.yaml
"""


def run_inference(config: dict):
    """Run inference exactly as described in the paper."""
    raise NotImplementedError
'''


def _smoke_test(slug: str) -> str:
    return f'''"""Smoke test: validates project wiring without heavy computation.

These tests must pass before any real experiment (see validation stage).
They check configuration parsing, module imports, and (when implemented)
that the pipeline runs end-to-end on a tiny input.
"""

import importlib
import os
import sys
import unittest

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "src"))


class SmokeTests(unittest.TestCase):
    def test_config_loads(self):
        import yaml

        with open("config.yaml", encoding="utf-8") as f:
            cfg = yaml.safe_load(f)
        self.assertIn("hyperparameters", cfg)
        self.assertIn("requirements", cfg)

    def test_modules_import(self):
        for mod in ("{slug.replace('-', '_')}.model",
                    "{slug.replace('-', '_')}.data",
                    "{slug.replace('-', '_')}.train"):
            importlib.import_module(mod)

    def test_build_model_signature(self):
        from {slug.replace('-', '_')}.model import build_model

        import yaml

        with open("config.yaml", encoding="utf-8") as f:
            cfg = yaml.safe_load(f)
        try:
            build_model(cfg)
        except NotImplementedError:
            pass  # scaffold not yet implemented: expected in generated project
        except Exception as e:  # pragma: no cover
            self.fail(f"build_model raised unexpected error: {{e}}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
'''


def _run_smoke(slug: str) -> str:
    return """#!/usr/bin/env bash
# Research RAG smoke run: syntax check + generated unit tests.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
"${PYTHON_BIN:-python}" -m compileall -q .
"${PYTHON_BIN:-python}" tests/test_smoke.py
echo SMOKE_OK
"""


def _readme(spec: ImplementationSpec, slug: str) -> str:
    reqs = spec.requirements
    by_source: dict[str, list] = {}
    for r in reqs:
        by_source.setdefault(r.source.value, []).append(r)
    lines = [
        f"# {slug.replace('-', ' ').title()}",
        "",
        f"Generated implementation project for **{spec.title}**.",
        "",
        "## Specification",
        "",
        spec.summary,
        "",
        f"Built from spec `{spec.id}` with {len(reqs)} requirements "
        f"({len(by_source.get('explicit', []))} explicit, "
        f"{len(by_source.get('inferred', []))} inferred).",
        "",
        "## Layout",
        "",
        "```",
        "config.yaml           # hyperparameters + requirement traceability",
        "src/{slug.replace('-', '_')}/       # model, data, train, evaluate, infer",
        "tests/test_smoke.py   # smoke tests (must pass before experiments)",
        "run_smoke.sh          # syntax check + smoke tests",
        "```",
        "",
        "## Usage",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "./run_smoke.sh",
        "```",
        "",
        "## Open questions (paper does not specify)",
        "",
    ]
    if spec.open_questions:
        lines += [f"- {q}" for q in spec.open_questions]
    else:
        lines.append("- (none recorded)")
    lines += ["", "## Provenance", ""]
    for r in reqs[:20]:
        page = f" p.{r.source_page}" if r.source_page else ""
        lines.append(f"- **{r.id}** [{r.source.value}]{page}: {r.requirement}")
    if len(reqs) > 20:
        lines.append(f"- … and {len(reqs) - 20} more (see config.yaml)")
    return "\n".join(lines) + "\n"


def _requirements_txt(spec: ImplementationSpec) -> str:
    deps = list(spec.dependencies)
    base = ["pyyaml"]
    out = sorted(set(base + [d.split("==")[0].strip() for d in deps]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# top-level
# ---------------------------------------------------------------------------

def generate_scaffold(spec: ImplementationSpec) -> list[GeneratedFile]:
    slug = project_slug(spec.title)
    pkg = slug.replace("-", "_")
    files = [
        GeneratedFile("README.md", _readme(spec, slug), kind="doc"),
        GeneratedFile("requirements.txt", _requirements_txt(spec), kind="deps"),
        GeneratedFile("config.yaml", _config_yaml(spec), kind="config"),
        GeneratedFile(f"src/{pkg}/__init__.py", f'"""{slug} (generated project)."""\n'),
        GeneratedFile(f"src/{pkg}/model.py", _model_py(spec, slug), kind="source"),
        GeneratedFile(f"src/{pkg}/data.py", _data_py(spec, slug), kind="source"),
        GeneratedFile(f"src/{pkg}/train.py", _train_py(spec, slug), kind="source"),
        GeneratedFile(f"src/{pkg}/evaluate.py", _evaluate_py(slug), kind="source"),
        GeneratedFile(f"src/{pkg}/infer.py", _infer_py(slug), kind="source"),
        GeneratedFile("tests/test_smoke.py", _smoke_test(slug), kind="test"),
        GeneratedFile("run_smoke.sh", _run_smoke(slug), kind="script"),
        GeneratedFile(".gitignore", "__pycache__/\n*.pyc\n.venv/\n"),
    ]
    return files
